foodie/config/routes.rb
Rails.application.routes.draw do
  resources :api_keys

  resources :foodies, except: [:new, :edit]
end

foodie/app/models/api_key.rb
class ApiKey < ActiveRecord::Base
end

foodie/app/models/food.rb
class Food < ActiveRecord::Base
end

foodie/app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base

  validates :username, presence: true
  validates :auth_token, presence: true

  before_validation on: :create do
    self.auth_token = SecureRandom.hex
  end
end

foodie/app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]

  # GET /api_keys
  # GET /api_keys.json
  def index
    @api_keys = ApiKey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_keys }
    end
  end

  # GET /api_keys/1
  # GET /api_keys/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_key }
    end
  end

  # GET /api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  # POST /api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to @api_key, notice: 'Api key was successfully created.' }
        format.json { render json: @api_key, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_keys/1
  # PATCH/PUT /api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1
  # DELETE /api_keys/1.json
  def destroy
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to api_keys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_key
      @api_key = ApiKey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_key_params
      params.require(:api_key).permit(:key, :name)
    end
end

foodie/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

foodie/app/controllers/foodies_controller.rb
require 'pry'
class FoodiesController < ApplicationController

  before_action :verify_api_key
  before_action :authenticate_user!

  def index
    @foods = Food.all
    render json: @foods
  end

  def create
    @food = Food.new(params.require(:food).permit(:name))
    @food.save
    render json: @food
  end

  def show
    @food = Food.find(params[:id])
    render json: @food
  end

  def update
    @food = Food.find(params[:id])
    @food.update(params.require(:food).permit(:name))
    render json: @food
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    render json: {ok: true}
  end

  def verify_api_key
    if ApiKey.find_by key: request.headers["x-api-key"]
    else
      render json: {"status" => "invalid_api_key"}, status: 401
    end
  end

  def authenticate_user!
    user = User.find_by auth_token: request.headers["x-auth-token"]
    if user
      @current_user = user
    else
      render json: {"status" => "Invalid or missing auth token"}, status: 401
    end
  end
end

foodie/app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

foodie/app/helpers/application_helper.rb
module ApplicationHelper
end

foodie/app/helpers/foodies_helper.rb
module FoodiesHelper
end

foodie/app/views/api_keys/_form.html.erb
<%= form_for(@api_key) do |f| %>
  <% if @api_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_key.errors.count, "error") %> prohibited this api_key from being saved:</h2>

      <ul>
      <% @api_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

foodie/app/views/api_keys/edit.html.erb
<h1>Editing api_key</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_key %> |
<%= link_to 'Back', api_keys_path %>

foodie/app/views/api_keys/index.html.erb
<h1>Listing api_keys</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @api_keys.each do |api_key| %>
      <tr>
        <td><%= api_key.key %></td>
        <td><%= api_key.name %></td>
        <td><%= link_to 'Show', api_key %></td>
        <td><%= link_to 'Edit', edit_api_key_path(api_key) %></td>
        <td><%= link_to 'Destroy', api_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api key', new_api_key_path %>

foodie/app/views/api_keys/new.html.erb
<h1>New api_key</h1>

<%= render 'form' %>

<%= link_to 'Back', api_keys_path %>

foodie/app/views/api_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @api_key.key %>
</p>

<p>
  <strong>Name:</strong>
  <%= @api_key.name %>
</p>

<%= link_to 'Edit', edit_api_key_path(@api_key) %> |
<%= link_to 'Back', api_keys_path %>

foodie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>